"""Constantes que representan reglas de negocio de UeesTask."""

PONDERACION_MINIMA = 1
PONDERACION_MAXIMA = 100
NOTA_MINIMA = 0
NOTA_MAXIMA = 100
MAX_CARACTERES_RETROALIMENTACION = 500
FORMATO_FECHA_NOTIFICACION = "%Y-%m-%d %H:%M"
